apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: CHARTNAME
version: 2.0.12
appVersion: 1.0.0
description: CHARTNAME App for TrueNAS SCALE
type: application
deprecated: false
home: https://github.com/cyr-ius/truenas-charts/tree/my-refs/charts/stable/CHARTNAME
icon: https://raw.githubusercontent.com/cyr-ius/truenas-charts/my-refs/stable/CHARTNAME/icon.png?raw=true
keywords:
  - CHARTNAME
sources:
  - https://github.com/cyr-ius/truenas-charts/tree/my-refs/charts/CHARTNAME
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 12.15.0
    # condition:
maintainers:
- email: cyr-ius@ipocus.net
  name: My Catalaog
  url: https://github/com/cyr-ius/
annotations:
  truecharts.org/catagories: |
    - media
    - test
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
