apiVersion: v2
name: cert-manager-webhook-pdns
version: 1.1.4
description: Cert Manager Webhook for PowerDNS.
type: application
home: https://github.com/cyr-ius/cert-manager-webhook-pdns
maintainers:
  - name: Cyr-ius
    email: webmaster@ipocus.net
    url: https://ipocus.net
appVersion: v1.1.4
