name: catalog_update

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    container:
      image: ixsystems/catalog_validation:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add catalog json as a safe directory
        run: |
          /bin/bash -c "PWD=${pwd}; git config --global --add safe.directory $PWD"
      - name: Publish catalog
        run: |
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/catalog_update publish --path $PWD"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Publish new changes in catalog
            commit_user_name: cyr-ius
            commit_user_email: cyr-ius@ipocus.net
            commit_author: cyr-ius <cyr-ius@ipocus.net>
      - name: Update catalog
        run: |
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/catalog_update update --path $PWD"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Publish new changes in catalog
            commit_user_name: cyr-ius
            commit_user_email: cyr-ius@ipocus.net
            commit_author: cyr-ius <cyr-ius@ipocus.net>
